name       : solvespace
version    : 3.1
release    : 1
source     :
    - git|https://github.com/solvespace/solvespace.git : v3.1
homepage   : https://solvespace.com/index.pl
license    : GPL-3.0-or-later
component  : office
summary    : Parametric 2d/3d CAD
description: |
    SOLVESPACE is a free (GPLv3) parametric 3d CAD tool.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(json-c)
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release -DENABLE_OPENMP=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
